Dockerfile, cicd-scripts/build.sh
https://github.com/open-cluster-management/backlog/issues/10311
=> add gitops to dockerfile

.travis.yml
https://github.com/open-cluster-management/backlog/issues/10311
=> disable release-ff and publish stage

CONTRIBUTING.md, Makefile
https://github.com/open-cluster-management/backlog/issues/10311
=> update makefile and contribution

.travis.yml
https://github.com/open-cluster-management/backlog/issues/10311
=> disable release-ff and publish

Makefile
Ref: https://github.com/open-cluster-management/backlog/issues/10140
=> support component image override.

cicd-scripts/setup-e2e-tests.sh
follow up PR for: https://github.com/open-cluster-management/observability-e2e-test/pull/117
=> fix copy path issue.

README.md
Ref: https://github.com/open-cluster-management/backlog/issues/10140
=> update readme for e2e testing.

cicd-scripts/e2e-setup-manifests/grafana/grafana-datasources-test.yaml, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
=> update observatorium cr name

pkg/tests/observability_addon_test.go
https://github.com/open-cluster-management/backlog/issues/10348
=> check new message in managedclusteraddon

pkg/tests/observability_metricslist_test.go, pkg/utils/mco_metric.go
Signed-off-by: Wei Shi <wshi@redhat.com>
=> Add test case for RHACM4K-1449

pkg/tests/observability_install_test.go, pkg/utils/mco_deploy.go
=> Fetch MCO CR from gitops repo

pkg/tests/observability_metricslist_test.go
https://github.com/open-cluster-management/backlog/issues/10810
=> disable the test for default allow list temporarily

cicd-scripts/setup-e2e-tests.sh, pkg/utils/mco_deploy.go
=> fix replace image issues by using kustomize

pkg/utils/mco_deploy.go
=> Use v1beta2

pkg/tests/observability_addon_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_custom_dashboards_test.go, pkg/tests/observability_default_config_test.go, pkg/tests/observability_endpoint_preserve_test.go, pkg/tests/observability_manifestwork_test.go, pkg/tests/observability_metricslist_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
1. reprioritize the test cases
2. re-enable some test cases which are disable in v1beta2 testing
=> reprioritize the test cases

pkg/tests/observability_observatorium_preserve_test.go
https://github.com/open-cluster-management/multicluster-observability-operator/pull/426
=> Update obs CR structure

pkg/tests/observability-e2e-test_suite_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
- Move reconcile testing out of aftersuite
- Disable switch from Basic to High mode
https://github.com/open-cluster-management/backlog/issues/10620
=> Move reconcile testing out of aftersuite

pkg/tests/observability_alert_test.go, pkg/utils/mco_deploy.go
https://github.com/open-cluster-management/backlog/issues/8803
Update component name with cr name as prefix.
=> update component name

pkg/tests/observability_default_config_test.go, pkg/tests/observability_install_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go, pkg/utils/utils.go
ref: https://github.com/open-cluster-management/backlog/issues/10852
depends on: https://github.com/open-cluster-management/observability-gitops/pull/11
=> add api conversion test cases.

pkg/tests/observability_install_test.go
=> Enhance beforesuite to report the real problem

pkg/tests/observability_addon_test.go, pkg/utils/mco_deploy.go, pkg/utils/mco_metric.go
- only print not ready pod status
- add nodeSelector test case
- modify log level and format
=> enhance test

Dockerfile, pkg/tests/observability_addon_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_custom_dashboards_test.go, pkg/tests/observability_default_config_test.go, pkg/tests/observability_endpoint_preserve_test.go, pkg/tests/observability_grafana_test.go, pkg/tests/observability_install_test.go, pkg/tests/observability_manifestwork_test.go, pkg/tests/observability_metricslist_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go
Triage the cases with stable and integration:
- stable case are tested in canary and pr
- integration cases are tested in pr
we can move the integration cases to stable cases once it is stable.
https://github.com/open-cluster-management/backlog/issues/11304
=> Triage the cases with stable and integration

pkg/tests/observability_install_test.go
https://github.com/open-cluster-management/backlog/issues/11377
=> Correct the logic

Dockerfile, format-results.sh
https://github.com/open-cluster-management/backlog/issues/11439
=> Format results for beforeSuite and afterSuite

cicd-scripts/grafana-dev-test.sh, pkg/tests/observability_grafana_dev_test.go
fixed https://github.com/open-cluster-management/backlog/issues/11237
=> add grafana-dev test

cicd-scripts/setup-e2e-tests.sh
=> clean up unused funcs from e2e setup.

pkg/tests/observability_addon_test.go
fix this error: https://travis-ci.com/github/open-cluster-management/multicluster-observability-operator/jobs/500263952#L966
=> add retry for mco addon test

README.md, pkg/tests/observability_retention_test.go
fixed https://github.com/open-cluster-management/backlog/issues/11629
Depends on https://github.com/open-cluster-management/observability-gitops/pull/13 and https://github.com/open-cluster-management/multicluster-observability-operator/pull/473
=> add retention test

pkg/tests/observability_addon_test.go, pkg/utils/mco_deploy.go
Add resource requirement e2e case for  endpoint-monitoring operator and metrics collector
https://github.com/open-cluster-management/backlog/issues/5764
/hold
=> add addon resource test

pkg/utils/mco_deploy.go
=> remove the hardcode the replicas

pkg/tests/observability-e2e-test_suite_test.go, pkg/tests/observability_install_test.go, pkg/utils/mco_pods.go
=> dump mco logs for critical failures.

pkg/tests/observability_install_test.go, pkg/utils/mco_deploy.go, pkg/utils/utils.go
=> fix resource ready check.

cicd-scripts/tests.sh, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
=> fix e2e due to fixed name

pkg/utils/mco_deploy.go, pkg/utils/utils.go
=> get the pullsecret from MCH CR

Dockerfile, cicd-scripts/build.sh
=> update branch for observability-gitops

pkg/tests/observability_reconcile_test.go
Blocking this PR - https://github.com/open-cluster-management/multicluster-observability-operator/pull/553
=> Disable customizing replicas

pkg/utils/mco_deploy.go
required change by https://github.com/open-cluster-management/multicluster-observability-operator/pull/553
=> move retentionConfig to advance section

pkg/tests/observability_install_test.go
https://github.com/open-cluster-management/backlog/issues/12718
=> add debug info when mco components is not ready

pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_install_test.go
- add retry for update mco
- check label for restarted pod
=> enhance e2e case

README.md, cicd-scripts/run-e2e-tests.sh, cicd-scripts/setup-e2e-tests.sh
=> fix e2e env clean and update doc.

observability_test.go, utils/mco_deploy.go
The PR was update the namespace to handle the e2e test in zstream of release-2.1
=> get the mch namespace when create the pullsecret

cicd-scripts/setup-e2e-tests.sh, pkg/tests/observability_advanced_config_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
fixed: https://github.com/open-cluster-management/backlog/issues/12863
=> Add tests for advanced configuration

pkg/tests/observability_addon_test.go, pkg/utils/mco_deploy.go
https://github.com/open-cluster-management/backlog/issues/12913
=> add debug info for addon test

pkg/tests/observability_addon_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_custom_dashboards_test.go, pkg/tests/observability_grafana_dev_test.go, pkg/tests/observability_metricslist_test.go, pkg/tests/observability_retention_test.go
- move the fallible case to the integration stage
- move the integration case to stable stage
=> update case stage

pkg/tests/observability_grafana_dev_test.go
ref: https://github.com/open-cluster-management/backlog/issues/13015
=> Disable grafana-dev test in canary environment

pkg/tests/observability_retention_test.go
used to fix the issue in QE's environment when the cluster have customized retention configed.
=> update the retention cases

pkg/tests/observability_alert_test.go, pkg/tests/observability_uninstall_test.go, pkg/utils/mco_deploy.go
https://travis-ci.com/github/open-cluster-management/canary/jobs/510573351#L771
https://github.com/open-cluster-management/backlog/issues/13060
=> enhance case

pkg/tests/observability_addon_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_install_test.go
- https://github.com/open-cluster-management/backlog/issues/13017
=> Fix e2e failure

pkg/tests/observability_cert_renew_test.go
Signed-off-by: Marco <llan@redhat.com>
=> refactoring for cert renew test

pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
https://github.com/open-cluster-management/backlog/issues/12393
depend on https://github.com/open-cluster-management/multicluster-observability-operator/pull/586
=> revert PR #185 related code

cicd-scripts/grafana-dev-test.sh
Exit once the command is failed, because the subsequent cannot be succeed.
=> Exit once failed

pkg/tests/observability_grafana_dev_test.go
We need to do more tests to enable this case. it is always failed so that block our PRs to be merged.
=> Skip grafana-dev tests

pkg/tests/observability_metricslist_test.go, pkg/utils/mco_metric.go
https://github.com/open-cluster-management/backlog/issues/13551
Signed-off-by: Marco <llan@redhat.com>
=> speed up to check stale metrics

pkg/utils/mco_deploy.go, pkg/utils/utils.go
- enhance log info
- check pod phase to print log
https://github.com/open-cluster-management/backlog/issues/13736
=> check pod phase to print log

pkg/tests/observability_alert_test.go
https://github.com/open-cluster-management/backlog/issues/13551
Signed-off-by: Marco <llan@redhat.com>
=> remove "offset 1m" from alert query

pkg/tests/observability_install_test.go
https://github.com/open-cluster-management/backlog/issues/13875
Signed-off-by: Marco <llan@redhat.com>
=> dont's uninstall mco if failed to checkmcoaddon in install step

pkg/tests/observability-e2e-test_suite_test.go
=> add log when test failed

pkg/tests/observability-e2e-test_suite_test.go, pkg/tests/observability_retention_test.go
=> the description did not have the updated value

cicd-scripts/setup-e2e-tests.sh
this fix the e2e broken issue for release-2.3
=> fix mco branch issue.

pkg/tests/observability_default_config_test.go, pkg/tests/observability_install_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go, pkg/utils/utils.go
used to fix https://github.com/open-cluster-management/backlog/issues/14099
=> [release-2.3]using the label selector

pkg/tests/observability-e2e-test_suite_test.go, pkg/tests/observability_advanced_config_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_endpoint_preserve_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/tests/observability_retention_test.go, pkg/utils/mco_deploy.go, pkg/utils/mco_deployments.go, pkg/utils/mco_statefulset.go
https://github.com/open-cluster-management/backlog/issues/14099
=> update to use lable selector for test cases

pkg/tests/observability_addon_test.go, pkg/tests/observability_advanced_config_test.go, pkg/utils/mco_deploy.go
used to fix the issue https://github.com/open-cluster-management/acm-qe/issues/355
=> add null spec check for advanced config test
