Makefile
Add e2e test placeholder target so that the rehearse tests of https://github.com/openshift/release/pull/16727 can pass.
=> add e2e test placeholder target.

cicd-scripts/setup-e2e-tests.sh
1. Fix copy issue during e2e test for MCO:
```
+ cp -r /go/src/github.com/open-cluster-management/multicluster-observability-operator/observability-e2e-test/../../multicluster-observability-operator /go/src/github.com/open-cluster-management/multicluster-observability-operator/observability-e2e-test
cp: cannot copy a directory, '/go/src/github.com/open-cluster-management/multicluster-observability-operator/observability-e2e-test/../../multicluster-observability-operator', into itself, '/go/src/github.com/open-cluster-management/multicluster-observability-operator/observability-e2e-test/multicluster-observability-operator'
```
2. Fix component image override issue, depends on https://github.com/open-cluster-management/multicluster-observability-operator/pull/393
=> fix copy path and component image override issues.

Dockerfile
Ginko has a new release. the skip test feature has changed in the new version. so we should use a fixed version for Ginko
=> fixed ginkgo version

pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_default_config_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go, pkg/utils/utils.go
Some properties are expired in v1beta2. for example: `availabilityConfig`. disable temporarily to make e2e test pass for v1beta2. Will re-enable it soon.
=> Disable some tests temporarily

pkg/tests/observability_metricslist_test.go, pkg/utils/mco_metric.go
Revert the following commits
dc32f10 2021-03-23 | Add test case for RHACM4K-1449 (#120) (tag: v2.3.0-2021-03-23-10-36-07) [Wei Shi]
59e6ba6 2021-03-24 | disable the test for default allow list temporarily (#132) (tag: v2.3.0-2021-03-25-01-47-24) [Ling Lan]
This test case is not needed because a single hardcore metrics test could be enough, no need to test all of them due to obs doesn't have code snip or path do handle each metrics.
=> Revert RHACM4K-1449 dc32f10

pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go, pkg/utils/mco_deployments.go
https://github.com/open-cluster-management/backlog/issues/8803
Add the following cases:
1. resize the alertmanager storage size
2. update the replicas for thanos-query from 2 to 3. the expected result is 3.
3. update  the replicas for thanos-query from 3 to 0. the expected result is 3.
4. 3. update  the replicas for thanos-query from 3 to 2. the expected result is 2.
=> Add cases for replicas and storage resize

pkg/tests/observability_install_test.go, pkg/tests/observability_observatorium_preserve_test.go
https://github.com/open-cluster-management/backlog/issues/11239
for the second time, the MCO CR status won't be updated. in other words, the MCO CR status is always ready after the first time. so we need to ensure all the components are ready before go to next step.
=> Ensure all required components are ready

pkg/tests/observability_addon_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_custom_dashboards_test.go, pkg/tests/observability_default_config_test.go, pkg/tests/observability_endpoint_preserve_test.go, pkg/tests/observability_grafana_dev_test.go, pkg/tests/observability_grafana_test.go, pkg/tests/observability_manifestwork_test.go, pkg/tests/observability_metricslist_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go
1. Print the cr/pod information if the current case is failed
2. Move `P2][Sev2][Observability][Integration] Should have no custom dashboard in grafana after related configmap removed (dashboard/g0)` to integration stage since we found this case is not stable enough.
https://github.com/open-cluster-management/backlog/issues/11833
=> Improve the tests

pkg/tests/observability_addon_test.go, pkg/tests/observability_grafana_test.go
To check the e2e test log,  it should be a timeout issue. so we should increase the timeout to waiting for metrics-collector ready.
https://github.com/open-cluster-management/backlog/issues/11951
=> increase timeout to waiting for metrics-collector ready

pkg/tests/observability_alert_test.go
This case is use to ensure we have --alertmanagers.url configured in rule. we found that it is broken by upstream code changes.
=> Check if --alertmanagers.url is configured in rule

Dockerfile
Correct the chain command to ensure the `format-results.sh` can be executed even if the first command is failed.
https://github.com/open-cluster-management/backlog/issues/12054
=> Correct the chain command

pkg/tests/observability_metricslist_test.go
if a metric name ending in `-`,  we will delete this metric from the default allowlist.
https://github.com/open-cluster-management/backlog/issues/12106
depend on https://github.com/open-cluster-management/observability-gitops/pull/21 and https://github.com/open-cluster-management/multicluster-observability-operator/pull/513
=> add deleted metrics test

pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
2 problem here:
1). the nodeSelector can be customized in the MCO CR, so if the nodeSelector did not set in the CR, we should skip the check.
2). the current key and value was hardcode, so the cases will be failed if the MCO CR have different value set.
Proposal:
1). before start the test, check if the MCO have nodeSelector set in the CR, if not, skip the test
2). when comparing the key and value, get the nodeSelector key and value from MCO CR and use this key and value to compare the nodeSelector in pod spec.
=> Do not hard code the nodeSelector

pkg/tests/observability_alert_test.go
--alertmanagers.url and --alertmanagers.config* parameters cannot be defined at the same time. we enable --alertmanagers.config-file to support forward alerts to hub alertmanager in new project.
=> enhance alertmanager config test.

pkg/tests/observability_install_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
since the mco operator may be installed in any of cluster, so we should not hardcode the namespace when get the mco operators pods.
=> remove the hardcoded namespace when get the mco pods

pkg/tests/observability_metricslist_test.go
https://github.com/open-cluster-management/backlog/issues/12106
depend on https://github.com/open-cluster-management/observability-gitops/pull/25 and  https://github.com/open-cluster-management/multicluster-observability-operator/pull/536 
=> add new test for delete metrics from match section

pkg/utils/mco_deploy.go
Move `retentionConfig` into `advanced` section in this PR - https://github.com/open-cluster-management/multicluster-observability-operator/pull/553
=> update retentionConfig in advanced

pkg/tests/observability_install_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
The PR was update the namespace to handle the e2e test in zstream of release-2.2
=> get the mch namespace when create the pullsecret

cicd-scripts/setup-e2e-tests.sh, pkg/tests/observability_addon_test.go, pkg/tests/observability_advanced_config_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_custom_dashboards_test.go, pkg/tests/observability_default_config_test.go, pkg/tests/observability_endpoint_preserve_test.go, pkg/tests/observability_grafana_dev_test.go, pkg/tests/observability_grafana_test.go, pkg/tests/observability_manifestwork_test.go, pkg/tests/observability_metricslist_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/tests/observability_retention_test.go
currently, we print all debug msg in every test case. even if the current case runs successfully. so we just need to show debug msg when the case failed.
=> only show debug msg when current case failed

pkg/tests/observability_grafana_dev_test.go
No need to run the SHELL Script repeated. if there is an error, then it must be wrong somewhere.
=> Simplify the grafana dev test

pkg/tests/observability_grafana_dev_test.go
We may meet Throttling during testing. Put `cmd.Run()` as arg of `Expect` is easy to timeout.
```
I0621 08:16:37.604198   10840 request.go:655] Throttling request took 1.165490291s, request: GET:https://api.ci-op-5r140n4g-7ee79.origin-ci-int-aws.dev.rhcloud.com:6443/apis/batch/v1beta1?timeout=32s
I0621 08:16:47.804184   10840 request.go:655] Throttling request took 11.365388486s, request: GET:https://api.ci-op-5r140n4g-7ee79.origin-ci-int-aws.dev.rhcloud.com:6443/apis/k8s.cni.cncf.io/v1?timeout=32s
deployment.apps "grafana-dev" deleted
I0621 08:16:55.345390   10859 request.go:655] Throttling request took 1.173074209s, request: GET:https://api.ci-op-5r140n4g-7ee79.origin-ci-int-aws.dev.rhcloud.com:6443/apis/networking.k8s.io/v1?timeout=32s
I0621 08:17:05.545378   10859 request.go:655] …
```
=> Expect has timeout

pkg/tests/observability_addon_test.go, pkg/tests/observability_advanced_config_test.go, pkg/tests/observability_alert_test.go, pkg/tests/observability_cert_renew_test.go, pkg/tests/observability_custom_dashboards_test.go, pkg/tests/observability_default_config_test.go, pkg/tests/observability_endpoint_preserve_test.go, pkg/tests/observability_grafana_dev_test.go, pkg/tests/observability_grafana_test.go, pkg/tests/observability_manifestwork_test.go, pkg/tests/observability_metricslist_test.go, pkg/tests/observability_observatorium_preserve_test.go, pkg/tests/observability_reconcile_test.go, pkg/tests/observability_retention_test.go
we should move `IntegrityChecking` to `JustAfterEach` block. because we need to catch the test status when `IntegrityChecking` failed.
https://github.com/open-cluster-management/backlog/issues/13968
=> mv IntegrityChecking to JustAfterEach

pkg/tests/observability_default_config_test.go, pkg/tests/observability_reconcile_test.go, pkg/utils/mco_deploy.go
1. if the MCO was created and already exists, no need to check the default value.
2. if the MCO CR did not have retentionConfig, update MCO will throws null point exception, so in this case, only update the storage size and test this part.
=> skip the cases when MCO was customized installation
